### PR TITLE
[995, 997, 1000, 1001, 1002]: Fix cosmetic issues

### LINKED ISSUE #995: Navigation links occupy two lines (1)
1. Text of the navigation links occupy two lines instead of one when screen width is between 992px and 1079px.

Comment: Enable the hamburger menu on 1080px.

### LINKED ISSUE #997: Buttons glow (9)
9. Gradient buttons and gradient text don’t have gradient glow as per the design.

Comment: Agree.

### LINKED ISSUE #1000: Animation on price filter (22)
22. We have only opening animation on price filter, do we need add animations on other filters/dropdowns?

Comment: Please remove animation of the price filter so we don't have any animations.

### LINKED ISSUE #1001: Horizontal scroll on mobile

### LINKED ISSUE #1002: Close button on mobile (14)

### PR DESCRIPTION
**Pull request by n0vax**
**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #995
Fixes #997 
Fixes #1000
Fixes #1001
Fixes #1002

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: src/providers/warning-provider/index.tsx [hunk 1]
```diff
@@ -87,14 +104,16 @@ const WarningProvider: React.FC = (props) => {
     };
   }
 
+  console.log({ warns });
+
```
Comment (failfmi) [inline src/providers/warning-provider/index.tsx:108]: nit

**Review by failfmi — APPROVED** [review]

**Review by failfmi — APPROVED** [review]
