### PR TITLE
[1014]: Jumping table size

### LINKED ISSUE #1014: Size of the table in Rent History section changes during loading (21)
Size of the table in Rent History section changes during loading. The same happens when we on some property page, but when rent history table in view Steps to reproduce:  * Go to my properties page (or refresh page if you already on this page) * During loading scroll down to the table in Rent History section 

Comment: Agree. Please fix.

### PR DESCRIPTION
**Pull request by n0vax**
**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #1014

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: src/modules/land-works/components/land-works-table-price/index.tsx [hunk 1]
```diff
@@ -15,46 +16,35 @@ interface ILandTablePriceProps {
   weiAmount: string;
   dateTimestamp: string;
 }
+
+const fetchTokenUsdPrice = async (tokenSymbol: string, timestamp: string) => {
+  if (tokenSymbol.toLowerCase() === 'usdc') {
+    return 1;
+  }
```
Comment (failfmi) [inline src/modules/land-works/components/land-works-table-price/index.tsx:23]: This is not correct

Comment (failfmi) [reply src/modules/land-works/components/land-works-table-price/index.tsx:23]: Use the price that you have like before.

Comment (n0vax) [reply src/modules/land-works/components/land-works-table-price/index.tsx:23]: Got you, I'll fix it
Btw, why are we using timestamp to calculate prices? 
I wanted to optimize calculation (fetch price only once instead of calculating it for each row) but because of the timestamp I didn't do it
Is it ok, if I omit timestamp and calculate prices based on the current exchange rate?

Comment (failfmi) [reply src/modules/land-works/components/land-works-table-price/index.tsx:23]: The idea is to show the $USD price when the transaction was executed, or at least the closest price to that "moment".

Comment (n0vax) [reply src/modules/land-works/components/land-works-table-price/index.tsx:23]: Ok, it's make sense, but if there are a lot of rows where we are fetching the price, it might not load it because of too many requests
