### PR TITLE
[653]: mine only lands

### LINKED ISSUE #653: Mine only toggle doesn't work on production
Bug was reported by a community member.
Below are screenshots he sent us:

### PR DESCRIPTION
**Pull request by mishaadzh**
**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #653 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: src/modules/land-works/views/explore-view/index.tsx [hunk 1]
```diff
@@ -169,17 +171,34 @@ const ExploreView: React.FC = () => {
...
+      if (owner?.length) {
+        const consumer = await fetchAllListedAssetsByConsumer(
+          String(metaverse),
+          lastRentEnd,
+          sortBySize ? 'totalRents' : orderColumn,
+          sortDir,
+          paymentToken,
+          owner
+        );
+        const mergedLands = union(lands.data, consumer.data);
```
Comment (failfmi) [inline src/modules/land-works/views/explore-view/index.tsx:183]: Wouldn't the sorting be broken after you union them?

Comment (mishaadzh) [reply src/modules/land-works/views/explore-view/index.tsx:183]: I`m not sure, but i tested with my lands and i not saw bugs

File: src/modules/land-works/constants.ts [hunk 2]
```diff
@@ -144,3 +144,15 @@ export const MY_PROPERTIES_TAB_STATE_LENT = 'lent';
 
 export const TWITTER_TEXT = `gm. Just listed my property at @landworksxyz.\n`;
 export const TWITTER_PROMOTE_TEXT = `gm. My property just became available at @landworksxyz.\n`;
+
+export const orderEnum: {
+  [key: string]: string;
+} = {
+  totalRents: 'totalRents',
+  pricePerSecond: 'pricePerMagnitude.price',
```
Comment (failfmi) [inline src/modules/land-works/constants.ts:152]: I think the sorting must be by `pricePerMagnitude.usdPrice`

**Review by failfmi — APPROVED** [review]
